Document: pastexen
Title: Debian pastexen Manual
Author: <insert document author here>
Abstract: This manual describes what pastexen is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pastexen/pastexen.sgml.gz

Format: postscript
Files: /usr/share/doc/pastexen/pastexen.ps.gz

Format: text
Files: /usr/share/doc/pastexen/pastexen.text.gz

Format: HTML
Index: /usr/share/doc/pastexen/html/index.html
Files: /usr/share/doc/pastexen/html/*.html
